name: Load Test with wrk2

on:
  workflow_dispatch:

jobs:
  load-test:
    strategy:
      matrix:
        include:
          - machine: 1
            base: 0
          - machine: 2
            base: 250000
          - machine: 3
            base: 500000
          - machine: 4
            base: 750000

    runs-on: ubuntu-latest
    name: Machine ${{ matrix.machine }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install wrk
        run: sudo apt-get install -y wrk

      - name: Run load test
        env:
          MACHINE_BASE: ${{ matrix.base }}
        run: wrk -t2 -c400 -d600s -s load-test.lua https://cdcserver.acropolis.teamzemo.tech